name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: digreatbrian/buildozer-action@v2
        with:
          buildozer_version: stable

      - uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
